export { default as Modal } from './modal/Modal'
export { default as Loading } from './loading/Loading'
export { default as LoadingSmall } from './loading/LoadingSmall'
export { default as Chatbot } from './chatbot/Chatbot'
export { default as NotFound } from './notfound/NotFound'
export { default as Headpage } from './headpage/Headpage'